remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "LPD"
description: "The Lego Pollution Department is an organisation whose aim is to restore coral back to the world's oceans."
